source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'cinch'
gem 'nokogiri'
gem 'httparty'
gem 'xbox_leaders'
gem 'google-api-client'
gem 'cinch-last_seen'
gem 'cinch-downforeveryone'
gem 'cinch-urbandictionary'
gem 'cinch-reddit'
